# Site Info
site_name: ebtel++
site_description: Efficient two-fluid hydrodynamic code for coronal loops
site_author: Will Barnes
site_url: 'https://rice-solar-physics.github.io/ebtelPlusPlus'

# Repository
repo_name: rice-solar-physics/ebtelPlusPlus
repo_url: https://github.com/rice-solar-physics/ebtelPlusPlus

# Navigation
docs_dir: mkdocs
nav:
- Getting Started: index.md
- Configuration: configuration.md
- Examples: examples.md
- API:
  - Classes: api/classes.md
  - Structs: api/structs.md
  - Typedefs: api/typedefs.md

# Appearance
theme:
  name: 'material'
  palette:
    primary: 'grey'
    accent: 'yellow'
  icon:
    logo: 'fontawesome/solid/code'

# Extensions
markdown_extensions:
  - codehilite
  - pymdownx.arithmatex

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Social/Contact
extra:
  social:
    - icon: 'fontawesome/solid/globe'
      link: 'http://solar.rice.edu/'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/rice-solar-physics'